version: '3.9'

services:
  db_multidesk:
    image: mysql:8.0
    container_name: mysql_db_multidesk
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: apiv1_multidesk
    volumes:
      - db_data_multidesk:/var/lib/mysql

  minio_multidesk:
    image: minio/minio:latest
    container_name: minio_multidesk
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    volumes:
      - minio_data_multidesk:/data
      - minio-policies_multidesk:/root/.minio/policies

  redis_multidesk:
    image: redis:latest
    container_name: redis_cache_multidesk
    ports:
      - "6379:6379"
    volumes:
      - redis_data_multidesk:/data

  myadmin_multidesk:
    image: phpmyadmin:latest
    container_name: myadmin_multidesk
    ports:
      - "8080:80" # Mapeia o phpMyAdmin para acesso via navegador (porta local: 8080)
    environment:
      PMA_HOST: db_multidesk # Conexão com o serviço "db_multidesk" no mesmo Compose
      PMA_USER: root       # Usuário (root por padrão)
      PMA_PASSWORD: ""     # Senha (pode ajustar caso necessário)

volumes:
  db_data_multidesk:
  redis_data_multidesk:
  minio_data_multidesk:
  minio-policies_multidesk: