name: Deploy Production Start

# Workflow acionado em pushes para a branch main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Check out code
        uses: actions/checkout@v4.2.2

      # Enviar notificação para o servidor de deployment
      - name: Trigger Deployment
        run: |
          curl -X POST http://178.156.141.41:3000/api/deploy/9bf56ab32c46997160e532adea77063d552dcff4e0e505f6