name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v4

      # Valida os arquivos composer.json e composer.lock
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Faz o cache dos pacotes do Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Instala as dependências
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      # Dispara o comando de deploy
      - name: Trigger Deployment
        run: |
          curl -X POST http://178.156.141.41:3000/api/deploy/9bf56ab32c46997160e532adea77063d552dcff4e0e505f6