name: PHP Composer

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v4

      # Valida os arquivos composer.json e composer.lock
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Faz o cache dos pacotes do Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Instala as dependências
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Faz push para a branch main
      - name: Push to main
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge dev
          git push origin main