name: PHP Composer

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v4

      # Valida os arquivos composer.json e composer.lock
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Faz o cache dos pacotes do Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Instala as dependências
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Faz push para a branch main
      - name: Push to main
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Verifica se a branch main existe e faz o checkout ou a cria
          if git show-ref --quiet refs/heads/main; then
            git checkout main
          else
            git checkout -b main origin/main || git checkout -b main
          fi

          # Sincroniza localmente a branch remota com pull
          git pull origin main --rebase

          # Faz o merge da branch dev na branch main
          git merge dev

          # Faz o push para a branch main no repositório remoto
          git push origin main --force-with-lease